// apps/angular/src/app/sidepanel/sidepanel-item/sidepanel-item.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-sidepanel-item',
  templateUrl: './sidepanel-item.component.html',
})
export class SidepanelItemComponent {
  @Input() clickId: string;
  @Input() label: string;
  @Output() action = new EventEmitter<any>();

  constructor() {
  }
}

<div class="item">
  <div class="key">
    {{label}}
  </div>
  <div class="value">
    <button
      [id]="clickId || ''"
      class="btn btn-outline-secondary btn-sm"
      (click)="action.emit()"
    >
      Apply
    </button>
  </div>
</div>

// apps/vuejs/src/components/sidepanel/SidepanelItem.vue
<template>
  <div class="item">
    <div class="key">
      {{label}}
    </div>
    <div class="value">
      <button
        :id="clickId || ''"
        class="btn btn-outline-secondary btn-sm"
        @click="$emit('action')"
      >
        Apply
      </button>
    </div>
  </div>

</template>

<script>
  export default {
    name: 'SidepanelItem',
    props: {
      clickId: String,
      label: String,
    }
  };
</script>

<style scoped>

</style>
