// apps/angular/src/app/sidepanel/sidepanel-body/sidepanel-body.component.ts
import { AfterContentChecked, Component } from '@angular/core';
import { TaskService } from "../../services/task.service";
import { ListTypeService } from "../../services/list-type.service";
import { TaskGeneratorService } from "../../services/task-generator.service";
import { startMeasure, stopMeasure } from '../../../../../angular-nativescript-app/app/perf-measure'

@Component({
  selector: 'app-sidepanel-body',
  templateUrl: './sidepanel-body.component.html',
})
export class SidepanelBodyComponent implements AfterContentChecked{

  constructor(public taskService: TaskService,
              public listTypeService: ListTypeService,
              public taskGeneratorService: TaskGeneratorService) {
  }

  genDefault() {
    startMeasure('generate Default');
    this.taskService.updateList(this.taskGeneratorService.default())
  }

  genRandom100() {
    startMeasure('generate Random 100');
    this.taskService.updateList(this.taskGeneratorService.random100())
  }

  genRandom500() {
    startMeasure('generate Random 500');
    this.taskService.updateList(this.taskGeneratorService.random500())
  }

  genRandom1k() {
    startMeasure('generate Random 1k');
    this.taskService.updateList(this.taskGeneratorService.random1k())
  }

  genRandom5k() {
    startMeasure('generate Random 5k');
    this.taskService.updateList(this.taskGeneratorService.random5k())
  }

  genRandom10k() {
    startMeasure('generate Random 10k');
    this.taskService.updateList(this.taskGeneratorService.random10k())
  }

  genRandom20k() {
    startMeasure('generate Random 20k');
    this.taskService.updateList(this.taskGeneratorService.random20k())
  }

  ngAfterContentChecked(): void {
    stopMeasure()
  }

}

<div class="sidepanel-body">
  <div class="section">
    <div class="name">
      Layout
    </div>
    <app-sidepanel-item
      clickId="layout-list"
      label="List"
      (action)="listTypeService.setListType('list')"
    ></app-sidepanel-item>
    <app-sidepanel-item
      clickId="layout-nested-list"
      label="Nested List"
      (action)="listTypeService.setListType('nested-list')"
    ></app-sidepanel-item>
    <app-sidepanel-item
      clickId="layout-grid"
      label="Grid"
      (action)="listTypeService.setListType('grid')"
    ></app-sidepanel-item>
  </div>

  <div class="section">
    <div class="name">
      Utils
    </div>
    <app-sidepanel-item
      clickId="utils-clearAll"
      label="Clear All"
      (action)="taskService.clearAll()"
    ></app-sidepanel-item>
  </div>

  <div class="section">
    <div class="name">
      Generators
    </div>
    <app-sidepanel-item
      clickId="gen-default"
      label="Default"
      (action)="genDefault()"
    ></app-sidepanel-item>
    <app-sidepanel-item
      clickId="gen-random100"
      label="Random 100"
      (action)="genRandom100()"
    ></app-sidepanel-item>
    <app-sidepanel-item
      clickId="gen-random500"
      label="Random 500"
      (action)="genRandom500()"
    ></app-sidepanel-item>
    <app-sidepanel-item
      clickId="gen-random1k"
      label="Random 1k"
      (action)="genRandom1k()"
    ></app-sidepanel-item>
    <app-sidepanel-item
      clickId="gen-random5k"
      label="Random 5k"
      (action)="genRandom5k()"
    ></app-sidepanel-item>
    <app-sidepanel-item
      clickId="gen-random10k"
      label="Random 10k"
      (action)="genRandom10k()"
    ></app-sidepanel-item>
    <app-sidepanel-item
      clickId="gen-random20k"
      label="Random 20k"
      (action)="genRandom20k()"
    ></app-sidepanel-item>
  </div>
</div>

// apps/vuejs/src/components/sidepanel/SidepanelBody.vue
<template>
  <div class="sidepanel-body">
    <div class="section">
      <div class="name">
        Layout
      </div>
      <SidepanelItem
        clickId="layout-list"
        label="List"
        @action="setListType('list')"
      ></SidepanelItem>
      <SidepanelItem
        clickId="layout-nested-list"
        label="Nested List"
        @action="setListType('nested-list')"
      ></SidepanelItem>
      <SidepanelItem
        clickId="layout-grid"
        label="Grid"
        @action="setListType('grid')"
      ></SidepanelItem>
    </div>

    <div class="section">
      <div class="name">
        Utils
      </div>
      <SidepanelItem
        clickId="utils-clearAll"
        label="Clear All"
        @action="clearAll()"
      ></SidepanelItem>
    </div>

    <div class="section">
      <div class="name">
        Generators
      </div>
      <SidepanelItem
        clickId="gen-default"
        label="Default"
        @action="genDefault()"
      ></SidepanelItem>
      <SidepanelItem
        clickId="gen-random100"
        label="Random 100"
        @action="genRandom100()"
      ></SidepanelItem>
      <SidepanelItem
        clickId="gen-random500"
        label="Random 500"
        @action="genRandom500()"
      ></SidepanelItem>
      <SidepanelItem
        clickId="gen-random1k"
        label="Random 1k"
        @action="genRandom1k()"
      ></SidepanelItem>
      <SidepanelItem
        clickId="gen-random5k"
        label="Random 5k"
        @action="genRandom5k()"
      ></SidepanelItem>
      <SidepanelItem
        clickId="gen-random10k"
        label="Random 10k"
        @action="genRandom10k()"
      ></SidepanelItem>
      <SidepanelItem
        clickId="gen-random20k"
        label="Random 20k"
        @action="genRandom20k()"
      ></SidepanelItem>
    </div>
  </div>

</template>

<script>
  import SidepanelItem from './SidepanelItem';
  import { mapMutations } from 'vuex';
  import { startMeasure } from '../../../../angular-nativescript-app/app/perf-measure';
  import { TaskGenerator } from '../../services/task-generator';

  export default {
    name: 'SidepanelBody',
    components: {SidepanelItem},
    methods: {
      ...mapMutations([
        'setListType',
        'updateList',
        'clearAll',
      ]),
      genDefault() {
        startMeasure('generate Default');
        this.updateList(TaskGenerator.default());
      },
      genRandom100() {
        startMeasure('generate Random 100');
        this.updateList(TaskGenerator.random100());
      },
      genRandom500() {
        startMeasure('generate Random 500');
        this.updateList(TaskGenerator.random500());
      },
      genRandom1k() {
        startMeasure('generate Random 1k');
        this.updateList(TaskGenerator.random1k());
      },
      genRandom5k() {
        startMeasure('generate Random 5k');
        this.updateList(TaskGenerator.random5k());
      },
      genRandom10k() {
        startMeasure('generate Random 10k');
        this.updateList(TaskGenerator.random10k());
      },
      genRandom20k() {
        startMeasure('generate Random 20k');
        this.updateList(TaskGenerator.random20k());
      },
    },
  };
</script>
