// apps/angular/src/app/task-grid/task-minimal/task-minimal.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { Task } from '../../../../../shared/models'

@Component({
  selector: 'app-task-minimal',
  templateUrl: './task-minimal.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TaskMinimalComponent {
  @Input() task: Task;

  constructor() {
  }
}

<div class="task-minimal">
  <label class="label">
    <input
      class="label__checkbox"
      type="checkbox"
      [(ngModel)]="task.isDone"
    />
    <span class="label__text">
          <span class="label__check">
            <i class="fa fa-check icon"></i>
          </span>
        </span>
  </label>
</div>

// apps/vuejs/src/components/task-grid/TaskMinimal.vue
<template>
  <div class="task-minimal">
    <label class="label">
      <input
        class="label__checkbox"
        type="checkbox"
        v-model="task.isDone"
      />
      <span class="label__text">
          <span class="label__check">
            <i class="fa fa-check icon"></i>
          </span>
        </span>
    </label>
  </div>

</template>

<script>
  export default {
    name: 'TaskMinimal',
    props: {
      task: Object
    }
  };
</script>

<style scoped>

</style>
