// apps/reactjs/src/task-list/Task.jsx
import * as React from 'react';
import { connect } from 'react-redux';

class Task extends React.PureComponent {

  constructor(props) {
    super(props);

    this.deleteTask = this.deleteTask.bind(this);
    this.handleInputChange = this.handleInputChange.bind(this);
  }

  deleteTask() {
    this.props.taskDeleted(this.props.task.id);
  }

  handleInputChange($event) {
    this.props.taskUpdated({
      ...this.props.task,
      isDone: $event.target.checked,
    });
  }

  render() {
    const {task} = this.props;
    return (
      <div className={`task ${task.isDone ? 'completed' : ''}`}>
        <div className="body">
          <div className="is-done-wrapper">
            <label className="label">
              <input
                className="label__checkbox"
                type="checkbox"
                checked={task.isDone}
                onChange={this.handleInputChange}
              />
              <span className="label__text">
                <span className="label__check">
                  <i className="fa fa-check icon"/>
                </span>
              </span>
            </label>
          </div>
          <span className="name">
            {task.name}
          </span>
          <div
            className="delete-wrapper"
            onClick={this.deleteTask}
          >
            <i className="fa fa-times"/>
          </div>
        </div>
      </div>

    );
  }
}

const mapStateToProps = state => ({});

const mapDispatchToProps = dispatch => ({});

export default connect(mapStateToProps, mapDispatchToProps)(Task);

// apps/vuejs/src/components/task-list/Task.vue
<template>
  <div
    class="task"
    :class="{completed: task.isDone}"
  >
    <div class="body">
      <div class="is-done-wrapper">
        <label class="label">
          <input
            class="label__checkbox"
            type="checkbox"
            v-model="task.isDone"
          />
          <span class="label__text">
          <span class="label__check">
            <i class="fa fa-check icon"></i>
          </span>
        </span>
        </label>
      </div>
      <span class="name">
      {{task.name}}
    </span>
      <div
        class="delete-wrapper"
        @click="deleteTask()"
      >
        <i class="fa fa-times"></i>
      </div>
    </div>
  </div>

</template>

<script>

  export default {
    name: 'Task',
    props: {
      task: Object,
      taskDeleted: Function,
    },
    methods: {
      deleteTask() {
        this.$emit('taskDeleted', this.task.id);
      },
    },
  };
</script>
