// apps/angular/src/app/task-list/task/task.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { Task } from '../../../../../shared/models'

@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TaskComponent {
  @Input() task: Task;
  @Output() taskDeleted = new EventEmitter<number>();

  constructor() {
  }

  deleteTask() {
    this.taskDeleted.emit(this.task.id)
  }
}

<div
  class="task"
  [ngClass]="{completed: task.isDone}"
>
  <div class="body">
    <div class="is-done-wrapper">
      <label class="label">
        <input
          class="label__checkbox"
          type="checkbox"
          [(ngModel)]="task.isDone"
        />
        <span class="label__text">
          <span class="label__check">
            <i class="fa fa-check icon"></i>
          </span>
        </span>
      </label>
    </div>
    <span class="name">
      {{task.name}}
    </span>
    <div
      class="delete-wrapper"
      (click)="deleteTask()"
    >
      <i class="fa fa-times"></i>
    </div>
  </div>
</div>

// apps/vuejs/src/components/task-list/Task.vue
<template>
  <div
    class="task"
    :class="{completed: task.isDone}"
  >
    <div class="body">
      <div class="is-done-wrapper">
        <label class="label">
          <input
            class="label__checkbox"
            type="checkbox"
            v-model="task.isDone"
          />
          <span class="label__text">
          <span class="label__check">
            <i class="fa fa-check icon"></i>
          </span>
        </span>
        </label>
      </div>
      <span class="name">
      {{task.name}}
    </span>
      <div
        class="delete-wrapper"
        @click="deleteTask()"
      >
        <i class="fa fa-times"></i>
      </div>
    </div>
  </div>

</template>

<script>

  export default {
    name: 'Task',
    props: {
      task: Object,
      taskDeleted: Function,
    },
    methods: {
      deleteTask() {
        this.$emit('taskDeleted', this.task.id);
      },
    },
  };
</script>
