// apps/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import {  TaskService } from "./services/task.service";
import { ListTypeService } from "./services/list-type.service";
import { ListType } from "../../../shared/models";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {

  constructor(public taskService: TaskService,
              public listTypeService: ListTypeService) {
  }

  setListType(listType: ListType) {
    this.listTypeService.setListType(listType);
  }
}

<!--suppress ALL -->
<div class="main-container">
  <div class="header-container">
    <h1>
      Todo List
    </h1>
    <app-task-creator></app-task-creator>

    <div class="info-bar">
      <div
        id="task-count"
        class="task-count"
      >
        {{taskService.getTasks().length}} tasks
      </div>
      <div class="list-types">
        <i
          class="fa fa-th-list list-type"
          [ngClass]="{selected: listTypeService.getListType() === 'list'}"
          (click)="setListType('list')"
          title="List"
        ></i>
        <i
          class="fa fa-briefcase list-type"
          [ngClass]="{selected: listTypeService.getListType() === 'nested-list'}"
          (click)="setListType('nested-list')"
          title="Nested List"
        ></i>
        <i
          class="fa fa-th list-type"
          [ngClass]="{selected: listTypeService.getListType() === 'grid'}"
          (click)="setListType('grid')"
          title="Grid"
        ></i>
      </div>
    </div>
  </div>
  <ng-container [ngSwitch]="listTypeService.getListType()">
    <app-task-list
      class="list-container"
      *ngSwitchCase="'list'"
    ></app-task-list>
    <app-task-grid
      class="grid-container"
      *ngSwitchCase="'grid'"
    ></app-task-grid>
    <app-task-list-nested
      class="list-container"
      *ngSwitchCase="'nested-list'"
    ></app-task-list-nested>
  </ng-container>
</div>
<app-sidepanel></app-sidepanel>

// apps/vuejs/src/App.vue
<template>
  <div id="app">
    <div class="main-container">
      <div class="header-container">
        <h1>
          Todo List
        </h1>
        <TaskCreator/>

        <div class="info-bar">
          <div
            id="task-count"
            class="task-count"
          >
            {{tasks.length}} tasks
          </div>
          <div class="list-types">
            <i
              class="fa fa-th-list list-type"
              title="List"
              :class="{selected: listType === 'list'}"
              @click="setListType('list')"
            ></i>
            <i
              class="fa fa-briefcase list-type"
              title="Nested List"
              :class="{selected: listType === 'nested-list'}"
              @click="setListType('nested-list')"
            ></i>
            <i
              class="fa fa-th list-type"
              title="Grid"
              :class="{selected: listType === 'grid'}"
              @click="setListType('grid')"
            ></i>
          </div>
        </div>
      </div>
      <TaskList
        class="list-container"
        v-if="listType === 'list'"
      />
      <TaskGrid
        class="grid-container"
        v-if="listType === 'grid'"
      />
      <TaskListNested
        class="list-container"
        v-if="listType === 'nested-list'"
      />
    </div>
    <Sidepanel/>
  </div>
</template>

<script>
  import { mapGetters, mapMutations } from 'vuex';
  import TaskCreator from './components/task-creator/TaskCreator';
  import TaskList from './components/task-list/TaskList';
  import TaskGrid from './components/task-grid/TaskGrid';
  import TaskListNested from './components/task-list-nested/TaskListNested';
  import { TaskGenerator } from './services/task-generator';
  import Sidepanel from './components/sidepanel/Sidepanel';

  export default {
    name: 'app',
    components: {
      Sidepanel,
      TaskListNested,
      TaskGrid,
      TaskList,
      TaskCreator,
    },
    computed: {
      ...mapGetters([
        'tasks',
        'listType',
      ]),
    },
    methods: mapMutations([
      'setListType',
      'updateList'
    ]),
    created() {
      this.updateList(TaskGenerator.default())
    },
  };
</script>

<style>
  @import "../../shared/global-styles.css";
</style>
