// apps/angular/src/app/task-list-nested/task-nested/task-nested.component.ts
import { Component, Input } from '@angular/core';
import { TaskService } from '../../services/task.service';

@Component({
  selector: 'app-task-nested',
  templateUrl: './task-nested.component.html',
})
export class TaskNestedComponent {
  @Input() index: number;

  constructor(public taskService: TaskService) {
  }
}

<div
  class="list-nested-micro-container"
  *ngIf="index < taskService.getTasks().length"
>
  <app-task
    [task]="taskService.getTasks()[index]"
    (taskDeleted)="taskService.deleteTask($event)"
  ></app-task>

  <app-task-nested
    [index]="index + 1"
    *ngIf="index + 1 <  taskService.getTasks().length"
  ></app-task-nested>
</div>

// apps/vuejs/src/components/task-list-nested/TaskNested.vue
<template>
  <div
    class="list-nested-micro-container"
    v-if="index < tasks.length"
  >
    <Task
      :task="tasks[index]"
      @taskDeleted="deleteTask"
    />

    <TaskNested
      :index="index + 1"
      v-if="index + 1 < tasks.length"
    />
  </div>

</template>

<script>
  import { mapGetters, mapMutations } from 'vuex'
  import Task from '../task-list/Task';

  export default {
    name: 'TaskNested',
    components: {Task},
    props: {
      index: Number
    },
    computed: {
      ...mapGetters([
        'tasks'
      ])
    },
    methods: {
      ...mapMutations([
        'deleteTask'
      ])
    }
  };
</script>

<style scoped>

</style>
