// apps/vuejs/src/components/task-creator/TaskCreator.vue
<template>
  <form
    @submit="taskName && createTask($event)"
  >
    <div class="input-group mb-3">
      <input
        type="text"
        class="form-control"
        placeholder="New task"
        v-model="taskName"
      />
      <div class="input-group-append">
        <button
          class="btn btn-outline-primary"
          type="submit"
          :disabled="!taskName"
        >
          <i class="fa fa-plus"></i>
          Add
        </button>
      </div>
    </div>
  </form>

</template>

<script>
  import { mapMutations } from 'vuex';

  export default {
    name: 'TaskCreator',
    data: () => ({
      taskName: '',
    }),
    methods: {
      createTask($event) {
        $event.preventDefault();

        this.addTask({
          name: this.taskName,
          isDone: false,
        });

        this.taskName = '';
      },
      ...mapMutations([
        'addTask',
      ]),
    },
  };
</script>

// apps/angular/src/app/task-creator/task-creator.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from "@angular/forms";
import { TaskService } from "../services/task.service";

@Component({
  selector: 'app-task-creator',
  templateUrl: './task-creator.component.html',
})
export class TaskCreatorComponent implements OnInit {
  newTaskForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private taskService: TaskService,
  ) {
  }

  ngOnInit() {
    this.newTaskForm = this.fb.group({
      taskName: this.fb.control("", Validators.required),
    });
  }

  createTask() {
    this.taskService.addTask({
      name: this.newTaskForm.value.taskName,
      isDone: false,
    });
    this.newTaskForm.reset();
  }

}

<form
  [formGroup]="newTaskForm"
  (ngSubmit)="newTaskForm.valid && createTask()"
>
  <div class="input-group mb-3">
    <input
      type="text"
      class="form-control"
      placeholder="New task"
      formControlName="taskName"
    />
    <div class="input-group-append">
      <button
        class="btn btn-outline-primary"
        type="submit"
        [disabled]="newTaskForm.invalid"
      >
        <i class="fa fa-plus"></i>
        Add
      </button>
    </div>
  </div>
</form>
